version: "3.8"

services:
  # Backend service
  backend:
    image: samontokarmaker/auth-nest:latest # our backend image from Docker Hub
    ports:
      - "5000:5000"  # Expose backend on port 5000
    depends_on:
      - postgres
    env_file:
      - ./.env  # Path to the backend .env file
    environment:
      NODE_ENV: production

  # PostgreSQL database service
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}  # Ensure these variables are set in the .env file
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env  # Path to the backend .env file

volumes:
  postgres_data:
